
import { Client } from '@/types/dashboard';

// Generate consistent demo client data
export const demoClients: Client[] = [
  { 
    id: 'client-001', 
    names: 'George & Lyn Whitehead', 
    location: 'Charlotte, North Carolina', 
    city: 'Charlotte',
    state: 'North Carolina',
    status: 'engaged', 
    department: 'sales', 
    roomNumber: '6391', 
    assignedAgent: 'Craig Boure',
    presentationTime: '12:30 PM',
    image: '/placeholder.svg'
  },
  { 
    id: 'client-002', 
    names: 'Malinda & Larry Jones', 
    location: 'Miami, Florida', 
    city: 'Miami',
    state: 'Florida',
    status: 'distracted', 
    department: 'sales', 
    roomNumber: '6391', 
    assignedAgent: 'Craig Boure',
    presentationTime: '12:30 PM',
    image: '/placeholder.svg'
  },
  { 
    id: 'client-003', 
    names: 'Philip & Traci Naegele', 
    location: 'Atlanta, Georgia', 
    city: 'Atlanta',
    state: 'Georgia',
    status: 'engaged', 
    department: 'finance', 
    roomNumber: '6393', 
    assignedAgent: 'Jennifer Williams',
    presentationTime: '3:30 PM',
    image: '/placeholder.svg'
  },
  { 
    id: 'client-004', 
    names: 'Scott & Renee White', 
    location: 'Dallas, Texas', 
    city: 'Dallas',
    state: 'Texas',
    status: 'engaged', 
    department: 'finance', 
    roomNumber: '6393', 
    assignedAgent: 'Jennifer Williams',
    presentationTime: '3:30 PM',
    image: '/placeholder.svg'
  },
  { 
    id: 'client-005', 
    names: 'Brian & Stephanie Miller', 
    location: 'Los Angeles, California', 
    city: 'Los Angeles',
    state: 'California',
    status: 'engaged', 
    department: 'sales', 
    roomNumber: '6392', 
    assignedAgent: 'Sarah Miller',
    presentationTime: '6:30 PM',
    image: '/placeholder.svg'
  },
  { 
    id: 'client-006', 
    names: 'David & Karen Thompson', 
    location: 'New York City, New York', 
    city: 'New York City',
    state: 'New York',
    status: 'away', 
    department: 'exit-survey', 
    roomNumber: '6395', 
    assignedAgent: 'Robert Davis',
    presentationTime: '6:30 PM',
    image: '/placeholder.svg'
  },
  { 
    id: 'client-007', 
    names: 'Robert & Lisa Anderson', 
    location: 'Phoenix, Arizona', 
    city: 'Phoenix',
    state: 'Arizona',
    status: 'distracted', 
    department: 'sales', 
    roomNumber: '6392', 
    assignedAgent: 'Sarah Miller',
    presentationTime: '8:00 PM',
    image: '/placeholder.svg'
  },
  { 
    id: 'client-008', 
    names: 'Michael & Jennifer Wilson', 
    location: 'Denver, Colorado', 
    city: 'Denver',
    state: 'Colorado',
    status: 'engaged', 
    department: 'finance', 
    roomNumber: '6394', 
    assignedAgent: 'Michael Johnson',
    presentationTime: '8:00 PM',
    image: '/placeholder.svg'
  },
  { 
    id: 'client-009', 
    names: 'James & Patricia Martinez', 
    location: 'Las Vegas, Nevada', 
    city: 'Las Vegas',
    state: 'Nevada',
    status: 'engaged', 
    department: 'sales', 
    roomNumber: '6394', 
    assignedAgent: 'Michael Johnson',
    presentationTime: '8:00 PM',
    image: '/placeholder.svg'
  },
  { 
    id: 'client-010', 
    names: 'John & Barbara Williams', 
    location: 'Seattle, Washington', 
    city: 'Seattle',
    state: 'Washington',
    status: 'distracted', 
    department: 'exit-survey', 
    roomNumber: '6395', 
    assignedAgent: 'Robert Davis',
    presentationTime: '12:30 PM',
    image: '/placeholder.svg'
  },
];
