// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwyiqesaktgqxwbgedip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3eWlxZXNha3RncXh3YmdlZGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTE0MTcsImV4cCI6MjA1OTQ4NzQxN30.NdIUoQtoO8I6yJvMIhq4IWJ4UxOt_lA_vdG3psGZRV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);